### ISSUE TITLE
[getValidation] Adding time execution

### ISSUE THREAD

**Issue by Daliben** [bleutner/RStoolbox#10]
Hello, 
I have a proposal,  in addition to "resultsValidation" that gives "getValidation", it will be better if the execution time (of"supclass") will be calculated and added to the validation results.
I need this for analysis please.
-------------------------------
Thank you :)
Daliben

**Comment by bleutner** [comment]
I'll consider that. But not right now, as it needs to be consistent across functions.
For the moment you could stop execution time yourself:

```r
## like this
begin <- Sys.time()
sc <- superClass(...)
Sys.time() - begin

# or  this
time <- system.time(sc <- superClass(...))
```

**Comment by Daliben** [comment]
Many thanks for your reply.
----
Daliben

**Comment by bleutner** [comment]
I decided not to add execution timing into the functions themselves since it is easy and more flexible to measure execution time externally as outlined in my comment above.
Thanks anyways for your suggestion.
