### ISSUE TITLE
Error in train.default(x, y, weights = w, ...) : Stopping

### ISSUE THREAD

**Issue by Daliben** [bleutner/RStoolbox#11]
Hi,
I have used the caret model "rotationForest" for supervised classification "superclass" , and the message error below appears:
---------------------------------------------------------------------------------------------
Something is wrong; all the Accuracy metric values are missing:
    Accuracy       Kappa    
 Min.   : NA   Min.   : NA  
 1st Qu.: NA   1st Qu.: NA  
 Median : NA   Median : NA  
 Mean   :NaN   Mean   :NaN  
 3rd Qu.: NA   3rd Qu.: NA  
 Max.   : NA   Max.   : NA  
 NA's   :9     NA's   :9    

Error in train.default(x, y, weights = w, ...) : Stopping
In addition: There were 50 or more warnings (use warnings() to see the first 50)
---------------------------------------------------------------------------------------------

N.B:
1.  the warnings message is in 'warning.txt'
[warning.txt](https://github.com/bleutner/RStoolbox/files/403520/warning.txt)

2.  I had the same error message by testing the caret model "AdaBoost".
3.  with the model "rf" everything goes well ( no error message).

Thanks in advance.
-----------------
Daliben

**Comment by bleutner** [comment]
Hi Daliben,

I just gave it a go and it works fine with both models.
Did you try to model more than two classes? Both AdaBoost and RotationForest are *two-class* models and fail if you feed them more than that...

For the future: it would be great if you could provide me with a [small, self-contained, reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) of the problem so I don't have to rely on guesses.

**Comment by Daliben** [comment]
Hi,
I have 15 classes, so the models "Adaboost andRandom forest" do not work?
Daliben.

**Comment by bleutner** [comment]
no

**Comment by mlnjsh** [comment]
Hi Daliben can you tell me the code for rotation forest in caret package

**Comment by Daliben** [comment]
Hi, 
I used this one:  https://cran.r-project.org/web/packages/rotationForest/index.html
