### ISSUE TITLE
readMeta displays acquisition time in local time zone without conversion

### ISSUE THREAD

**Issue by mraraju** [bleutner/RStoolbox#12]
First of all, I thank the author for developing this tool which is very useful. It would be nice to correct this minor issue in readMeta.R. The use of the function as.POSIXlt on scene_center_time variable without parameter 'tz=GMT', simply adds local time zone tag (in my case IST) to the time value. 

$ACQUISITION_DATE
[1] "2000-04-10 04:57:51 IST"

This made me to convert the time value back to GMT by subtracting 5.30 from the time value displayed by readMeta, which was wrong as the time value was already denoting GMT but wrongly tagged with local time zone. (I found the issue with clues from sun azimuth and elevation angles.). I request you to either add the parameter 'tz="GMT"' to as.POSIXlt or correct the time value with respect to the time zone of the scenes. Once again I thank u for such a nice tool.

**Comment by bleutner** [comment]
Thanks for spotting this. Should now be fixed.
