### ISSUE TITLE
pifMatch Pseudo-Invariant Features based Image Matching

### ISSUE THREAD

**Issue by tmb3006** [bleutner/RStoolbox#13]
I believe there is a issue with pifmatch returning the adjusted image.
"Value
Returns a RasterStack with the adjusted image (img) by default"

The only return I see when running your default code is the pixel-wise similarity map $simMap 

```r
library(gridExtra)
## Import Landsat example data
data(lsat)
## Create fake example data
## In practice this would be an image from another acquisition date
lsat_b <- log(lsat)
## Run pifMatch
lsat_b_adjusted <- pifMatch(lsat_b, lsat)
```

**Comment by bleutner** [comment]
Should work now. Thanks for reporting.
