### ISSUE TITLE
unsuperClass creating a map with more classes than defined

### ISSUE THREAD

**Issue by everydayduffy** [bleutner/RStoolbox#14]
Using a single raster layer as input containing values from 0-228.1111, the output contains 5 classes instead of the requested 2. 

Example code:
`out <- unsuperClass(subset(focal.stack,names(focal.stack)[i],nClasses=2))`

**Comment by bleutner** [comment]
I cannot reproduce this. Can you please provide a small data set, where this happens?

**Comment by everydayduffy** [comment]
Hi Benjamin,

Sorry, there isn't a problem now. I had a bracket in the wrong place, it should be:

`out <- unsuperClass(subset(focal.stack,names(focal.stack)[i]),nClasses=2)`

Looks like `nClasses` was passed to subset, and the default (which I believe is 5?) was used for `unsuperClass`.

**Comment by bleutner** [comment]
OK, thanks.
