### ISSUE TITLE
Error in running RotationForest in caret

### ISSUE THREAD

**Issue by mlnjsh** [bleutner/RStoolbox#15]
cctrl <- trainControl(method = "cv", number = 3, returnResamp = "all",
                       classProbs = TRUE, 
                       summaryFunction = twoClassSummary)
                       
fit <- train(Class ~ ., data = training, 
                            method = "rotationForest", 
                            trControl = cctrl1,
                            metric = "ROC", 
                            preProc = c("center", "scale"))

Giving me error **"Model rotationForest is not in caret's built-in library"**

**Comment by bleutner** [comment]
This is not related to the RStoolbox package but to the caret package. I guess you just misspelled the method (check the docs for the correct acronym). If there still is an issue you should contact the caret maintainer.
