### ISSUE TITLE
[SuperClass] Comparison Classification Accuarcies

### ISSUE THREAD

**Issue by Daliben** [bleutner/RStoolbox#16]
Hi, 
I want to know how can I compare the results of classification (Accuarcy, kappa) of two or three models (such as RF, SVM and LDA for example) after using superclass. How can I use for example: "Box and Whisker Plots" or "Density Plots" and "Scatterplot Matrix" or others techniques to illustrate the estimated accuracy by the differents models.
Thanks.
------------
Daliben

**Comment by bleutner** [comment]
Dear Daliben, 

this site is intended for reporting bugs on RStoolbox only and I'm happy if you do report actual bugs. 
Please understand, however, that I cannot provide tech support here. 
There are dedicated places, where you can post such questions, such as stackoverflow.com, stats.stackoverflow.com or R mailing lists. 
My last advice for your specific question, before I close this "issue",  is to check-out the book by Kuhn et al. on "Predictive modelling".

Cheers,
Benjamin

**Comment by Daliben** [comment]
OK , thanks.
---------------
Daliben
