### ISSUE TITLE
[superclass_getvalidation] return of final values of model parameters

### ISSUE THREAD

**Issue by Daliben** [bleutner/RStoolbox#18]
Hello,
"superclass"  uses “tuneLength” argument to indicate the number of different values to try for each model parameter and uses also the k fold cross validation for resampling during model tuning. 
Please, is it possible that «get validation function" provides the final values tuned used of the caret model ? 
For example: for  the  model “svmRadial”,  the  final values of two parameters (sigma)and  Cost (C) used on classification task will be returned also as results of getvalidation.  
Thanks in advance.

**Comment by Daliben** [comment]
Hi, 
I’m waiting for your reply; please I really need it for urgent analysis.
Thanks in advance.
Daliben.

**Comment by bleutner** [comment]
Hi Daliben, 

I'm yet undecided whether I will add this to `getValidation()`, because strictly speaking it has little to do with validation.

However you can easily grab the selected hyperparameters yourself like this:
```r
SC <- superClass(...)
SC$model$bestTune
```

or in case your're interested in the full tuning profile, you'll find the results here:
```r
SC$model$results
```

Does that help?

**Comment by Daliben** [comment]
Hi, 
Yes it's very helpful. Many thanks.

**Comment by bleutner** [comment]
ok, I'll close this then.

**Comment by Daliben** [comment]
Hi,
Please, i want to know, if the different values to be tried for each algorithm parameter are set randomly and automatically ? (Automatic Grid)
Daliben.
Thanks in advance.

**Comment by bleutner** [comment]
It uses an automatic grid search, i.e. not random. The way the grid is defined is different for each model type and is specified in the caret modelInfo. The function to calculate the grid can be retrieved like this: 
```r
## example for random forest
mod <- "rf"
caret::getModelInfo(mod, regex = FALSE)[[mod]]$grid
```
For details on the grid function see [here.](https://topepo.github.io/caret/using-your-own-model-in-train.html)

You can override the automatic grid construction with your own grid if you wish. For this use the tuneGrid parameter in superClass:
```r
## example for random forest:
superClass(..., tuneGrid=data.frame(mtry=c(1,5,6)))
```

**Comment by Daliben** [comment]
Thank you very mach for the answer.
Daliben.
