### ISSUE TITLE
rasterCVA function: error "cannot use this formula, probably because it is not vectorized"

### ISSUE THREAD

**Issue by MarkusMartini** [bleutner/RStoolbox#19]
Dear all,
I try to use the rasterCVA function on two bands of two Landsat 5 images (with the same extent), but I receive an error, as seen in the following:

`changeVec <- rasterCVA(LS_Aug_2011[[3:4]], LS_Aug_2010[[3:4]])
Error in (function (x, fun, filename = "", recycle = TRUE, ...)  : 
  cannot use this formula, probably because it is not vectorized`

Here some details about my raster objects:

`
> LS_Aug_2011
class       : RasterBrick 
dimensions  : 7421, 8221, 61008041, 7  (nrow, ncol, ncell, nlayers)
resolution  : 30, 30  (x, y)
extent      : 173985, 420615, 4989285, 5211915  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=35 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0 
data source : /home/gce04/C7_Martini_2017/landsat_data/LS_Aug_2011_stack.tif 
names       : LS_Aug_2011_stack.1, LS_Aug_2011_stack.2, LS_Aug_2011_stack.3, LS_Aug_2011_stack.4, LS_Aug_2011_stack.5, LS_Aug_2011_stack.6, LS_Aug_2011_stack.7 
min values  :                   0,                   0,                   0,                   0,                   0,                   0,                   0 
max values  :                 255,                 255,                 255,                 255,                 255,                 182,                 255 

> LS_Aug_2010
class       : RasterBrick 
dimensions  : 7421, 8221, 61008041, 7  (nrow, ncol, ncell, nlayers)
resolution  : 30, 30  (x, y)
extent      : 173985, 420615, 4989285, 5211915  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=35 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0 
data source : /home/gce04/C7_Martini_2017/landsat_data/LS_Aug_2010_stack.tif 
names       : LS_Aug_2010_stack.1, LS_Aug_2010_stack.2, LS_Aug_2010_stack.3, LS_Aug_2010_stack.4, LS_Aug_2010_stack.5, LS_Aug_2010_stack.6, LS_Aug_2010_stack.7 
min values  :                   0,                   0,                   0,                   0,                   0,                   0,                   0 
max values  :                 255,                 255,                 255,                 255,                 255,                 180,                 255 
`

Can you help me out with that issue?

Looking forward to comments.

Cheers!

**Comment by bleutner** [comment]
i can't reproduce this here.

Does it happen also if you run the example from `?rasterCVA` ?
if not, could you please assemble a reproducible example for me? 
Plus posting the output of  devtools::session_info()

**Comment by MarkusMartini** [comment]
Dear bleutner,
the example worked fine. After sub-setting the data to a smaller extent rasterCVA worked fine, so assume the error occurred due to NAs present in the complete images. If you like I am happy to share the data with you off-site. Thanks!

**Comment by bleutner** [comment]
Still can't reproduce it. It works fine for me with NAs, even if all pixels are NA.
So yes, please send me your example data.
