### ISSUE TITLE
Column names for "x" object

### ISSUE THREAD

**Issue by topepo** [bleutner/RStoolbox#22]
I've made a change to `caret:::train` that requires the predictor matrix (`x`) to always have column names and that breaks your test:
```
  > test_check("RStoolbox")
  Loading required package: sp
  1. Error: predict mlc (@test-mlc.R#16) -----------------------------------------
  Please use column names for `x`
  1: train(mat, y, method = mlcCaret, trControl = trainControl(method = "none")) at testthat/test-mlc.R:16
  2: train.default(mat, y, method = mlcCaret, trControl = trainControl(method = "none"))
  3: stop("Please use column names for `x`", call. = FALSE)
  
  testthat results ================================================================
  OK: 726 SKIPPED: 0 FAILED: 1
  1. Error: predict mlc (@test-mlc.R#16) 
``` 
I have a version set to CRAN that found this. Can you update your test (and perhaps relevant parts of the package) to have column names?  If this is a big deal, I can just set names if there are none but that seems like a poor solution (but feedback is welcome). 

Thanks

**Comment by bleutner** [comment]
It was only the test that needed fixing. I'll do my checks and submit it to CRAN asap.

**Comment by topepo** [comment]
Great! thanks
