### ISSUE TITLE
New landsat product identifier

### ISSUE THREAD

**Issue by soilscience** [bleutner/RStoolbox#23]
Hello, 

I have been trying to run RSToolbox on the latest LandSat8 images (Collection 1 product identifiers have changed) and some of the functions fail to run with an error invalid layer names. I have been trying to change the functions radCor and stackMeta to run on the new datasets (Data from the MTL file has longer row names and band names[i've changed it back to B1_dn etc.)) and changed the data from MTL file to look similar to the pre collection versions of landsat images. This solved the invalid layer names issue, but now it fails at the .LANDSAT.db object. Is it a known issue or i am doing something wrong (my code was perfectly running on the pre collection versions) Thanks in advance L.

Oh and I am running RStudio v1.0.143 with R version 3.3.2 on a Win 10 machine.

The code is simple:

SatFolder is an unchanged unpacked LS folder with all original files (MTL and all bands)
(eg: F:/.../LC81880272017086LGN00

mtlFile<-list.files(SatFolder, pattern = glob2rx("*_MTL.txt"), full.names = TRUE)
metaData <- readMeta(mtlFile)
lsat <- stackMeta(mtlFile)
lsat_ref <- radCor(lsat, metaData = metaData, method = "apref")

**Comment by soilscience** [comment]
Oh and I am running RStudio v1.0.143 with R version 3.3.2 on a Win 10 machine.

**Comment by bleutner** [comment]
Hi, 

I just tried with a collection 1 Landsat 8 scene and it worked without issues.

Are you running the latest RStoolbox version? (v0.1.8)
`installed.packages()["RStoolbox","Version"]`

Which is the scene identifier (or path/row and date) of your scene that fails? `LC81880272017086LGN00` indicates a pre-collection scene.

**Comment by soilscience** [comment]
Hi Benjamin, 

You are right I'm running v0.1.6. My bad. I will update and check it again ASAP.
Yes the example was a precollection one I had this in my code at that time.

I was testing it on this one (189;027):
LC08_L1TP_189027_20170403_20170414_01_T1.tar

I will rerun it and give a feedback.

Thanks for the help.

**Comment by soilscience** [comment]
Dear Benjamin, 

Thanks for the help, and for developing and updating this package. Worked like a charm after updating to latest version.
Sorry for bothering with this amateur mistake.

Cheers

**Comment by bleutner** [comment]
no problem
