### ISSUE TITLE
Problems installing package on Ubuntu 16.04

### ISSUE THREAD

**Issue by valpesendorfer** [bleutner/RStoolbox#24]
I'm not able to install the package on my Ubuntu server. It fails with the following step:

configure: Need to download and build NLopt
trying URL 'http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz'
Error in download.file(url = "http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz",  : 
  cannot open URL 'http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz'
In addition: Warning message:
In download.file(url = "http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz",  :
  URL 'http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz': status was 'Failure when receiving data from the peer'
Execution halted
Error in file(con, "rb") : cannot open the connection
Calls: untar -> readBin -> file
In addition: Warning message:
In file(con, "rb") :
  cannot open file 'nlopt-2.4.2.tar.gz': No such file or directory
Execution halted
configure: Starting to install library to /tmp/Rtmp9oSNpM/R.INSTALL32603998a7/nloptr/nlopt-2.4.2
./configure: line 3325: cd: nlopt-2.4.2: No such file or directory

Thanks

**Comment by bleutner** [comment]
The nlopt server seems down at the moment (same for me), I guess that's only temporary. Its a bit unusual for cran packages, but nlopt source code is pulled in from this external/non-CRAN server and then compiled,

If you have root access on your server you could just install the pre-compiled package instead
`sudo apt install r-cran-nloptr`

**Comment by valpesendorfer** [comment]
I was already assuming this to be the case. 
The server is up again and the package installs without error now. Thanks for the quick support!
