### ISSUE TITLE
Read EarthExplorer new CSV files

### ISSUE THREAD

**Issue by dpoursanidis** [bleutner/RStoolbox#25]
Hi,

Congrats for the tool (any future update for Sentinels?) ! I try to read and plot the new CSV files from EarthExplorer (Collection 1) but couldn't have "acceptable"results following the code example in the vignette. Attached the csv i try to plot and read.
[LSR_LANDSAT_TM_C1_189326.zip](https://github.com/bleutner/RStoolbox/files/1148018/LSR_LANDSAT_TM_C1_189326.zip)

Best
D.

**Comment by bleutner** [comment]
Hi, sorry for taking so long. Fixed in the next release / current master branch.

I'm planning to add a metadata reader for Sentinel2, yes. But that'll be around November.
