### ISSUE TITLE
Landsat 8 Level 1 product read

### ISSUE THREAD

**Issue by iqbalhabibie** [bleutner/RStoolbox#29]
from your webpage http://bleutner.github.io/RStoolbox/rstbx-docu/readMeta.html

## Example metadata file (MTL)
mtlFile  <- system.file("external/landsat/LT52240631988227CUB02_MTL.txt", package="RStoolbox")

## Read metadata
metaData <- readMeta(mtlFile)

## Summary
summary(metaData)

I change to : 
mtfile<- system.file("MTL.txt", package = "RStoolbox")
meta<- readMeta("Directory/MTL.txt")
summary(meta)

**Comment by bleutner** [comment]
Please describe your problem if there is one.

**Comment by iqbalhabibie** [comment]
Yes I am using your readMeta is cant use, and the error is "Error: Metadata file does not exist. Looking for:" so I change the the script it can be read like I mention above. I try this on RStudio and R is not working and I use github package. I wonder what is the problem?

**Comment by bleutner** [comment]
Again, your file paths are wrong. 
You need to give the **correct location** of a file on **your** computer.
The `system.file()` command is only needed to load the example data which ship with the package.
