### ISSUE TITLE
EVI

### ISSUE THREAD

**Issue by PauloEduardoCardoso** [bleutner/RStoolbox#3]
Considering that spectralIndices() do not rescale G, C1 and C2, shouldn't EVI index be obtained for toa or sr values but not for dn?

SI <- spectralIndices(lsat, red = "B3_dn", nir = "B4_dn", blue='B2_dn')
plot(SI)
![sidn](https://cloud.githubusercontent.com/assets/173906/10007842/b3310f54-60c0-11e5-88ed-95f2430e311f.jpeg)

lsat_sref0<- radCor(lsat, metaData = metaData0, method = "dos")
SI <- spectralIndices(lsat_sref0, red = "B3_sre"
                      , nir = "B4_sre"
                      , blue='B2_sre', indices = "EVI")
plot(SI)
![sisre](https://cloud.githubusercontent.com/assets/173906/10007873/edbbd1cc-60c0-11e5-8198-58e1514ae55c.jpeg)

A warning could/should be provided or sre bands computed instead.

**Comment by bleutner** [comment]
Thanks!
I have now restricted the calculation of EVI or EVI2 to reflectance values.
To do this I check for values outside of [0,1]. If this is met, I check whether the EVI coefficients have been changed from the default. If that's not the case, I throw a warning and exclude calculation of EVI / EVI2.

Options are then to either provide reflectance data in [0,1]  or to rescale the coefficients manually.
