### ISSUE TITLE
Example ENVI spectral libraries

### ISSUE THREAD

**Issue by iqbalhabibie** [bleutner/RStoolbox#30]
Reading RStoolbox\external 

## Example data
sliFile <- system.file("external/vegSpec.sli", package="RStoolbox")
sliTmpFile <- paste0(tempdir(),"/vegetationSpectra.sli") 

## Read spectral library
sli <- readSLI(sliFile)
head(sli)

I change to 

sfile<- system.file("vegSpec.sli", package = "RStoolbox")
meta<- system.file("C:/RStoolbox/external/landsat/vegSpec.sli")
sliTmpFile<- paste0(tempdir(),"C:/RStoolbox/external/landsat/vegetationSpectra.sli")
sli <- readSLI(meta)
Error in readBin(f, "int", 1000, size = 1, signed = FALSE) :
  can only read from a binary connection
In addition: Warning message:
In file(path, "rb", raw = TRUE) :
  file("") only supports open = "w+" and open = "w+b": using the former

I would like to know what is the problem?

**Comment by bleutner** [comment]
your pointing to non-existent files. this is not an RStoolbox issue.
