### ISSUE TITLE
using factors in caret::confusionMatrix

### ISSUE THREAD

**Issue by topepo** [bleutner/RStoolbox#38]
The version of caret being sent to CRAN (6.0-79) has a change that affects your package. The details are here: 

   https://github.com/topepo/caret/commit/e4dc43d679f25f7289b835c29dfbae1527c7f880 

In summary, when creating a confusion matrix using two vectors, the input data are now required to be factors with the same levels. If this is an issue, you can get around it by creating a table and using `confusionMatrix.table` to get around the requirement.   

The issues for your respective packages are shown below. When you submit to CRAN, please make sure that the dependency has `caret (>= 6.0-79)`.  

Let me know if you have any questions.  

Thanks, 

Max 

    ```
     ERROR
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      ── 2. Error: classification, with class mapping (@test-validateMap.R#26)  ──────
      `data` and `reference` should be factors with the same levels.
      1: validateMap(sc$map, valData = poly, nSample = 100, responseCol = "class", classMapping = sc$classMapping) at testthat/test-validateMap.R:26
      2: confusionMatrix(valiSet[[1]][, "prediction"], reference = valiSet[[1]][, "reference"])
      3: confusionMatrix.default(valiSet[[1]][, "prediction"], reference = valiSet[[1]][, 
             "reference"])
      4: stop("`data` and `reference` should be factors with the same levels.", call. = FALSE)
      
      ══ testthat results  ═══════════════════════════════════════════════════════════
      OK: 926 SKIPPED: 2 FAILED: 2
      1. Error: classification, without class mapping (@test-validateMap.R#19) 
      2. Error: classification, with class mapping (@test-validateMap.R#26) 
      
      Error: testthat unit tests failed
      Execution halted
    ```

**Comment by bleutner** [comment]
fixed on CRAN
