### ISSUE TITLE
How do we parallel the RStoolbox?

### ISSUE THREAD

**Issue by harryprince** [bleutner/RStoolbox#46]
I am preparing training data for keras GAN model, which need to crop lots of raster images to jpeg images. Does anyone have an idea how to parallel this process? Is Spark or doParallel the candidate?

**Comment by bleutner** [comment]
For croppying you should use either gdal directly on your OS command line or, if you must use R, then use gdalUtils::gdalwarp() and gdalUtils::gdal_translate(). gdalwarp has a multithreaded implementation which you can activate by setting multi=TRUE.

For running RStoolbox functions in parallel use raster::beginCluster() once beforehand.
