### ISSUE TITLE
readSLI: take byte order of hdr into consideration

### ISSUE THREAD

**Issue by aloboa** [bleutner/RStoolbox#47]
When I use readSLI() to read a library with byte order = 1 in its hdr, I get weird values in R, while libraries
that have byte order = 0  result in R obkects with meaningful values. 
byte order = 1 : https://lost-contact.mit.edu/afs/enea.it/software/rsi/envi_3.5/spec_lib/jpl_lib/
byte order = 0: https://lost-contact.mit.edu/afs/enea.it/software/rsi/envi_3.5/spec_lib/usgs_min/

I understand that readSLI() assumes byte order = 0 (least significant byte first (LSF) data ),
am I wrong? 
If I'm not wrong, could byte order be taken into account by readSLI() ?

**Comment by aloboa** [comment]
I'm trying to modify readSLI() locally on my own, but as soon as I do it with
fix(readSLI)
upon running I get:
Error in .getNumeric(hdr[grep("samples", hdr)]) : 
  could not find function ".getNumeric"

using a windows box (today) and the github version o RStoolbox

**Comment by aloboa** [comment]
I have circumvented the problem by including .getNumeric() and .bracketRange() in a modified local version
of readSLI() and it works. 
The only diferences to the original readSLI() are:
change
```
        data_type  <- .getNumeric(hdr[grep("data type", hdr)])
        id <- .bracketRange(hdr, "spectra names")
```
to
```
        data_type  <- .getNumeric(hdr[grep("data type", hdr)])
        byte_order <- .getNumeric(hdr[grep("byte order", hdr)])
        byte_order <- ifelse(byte_order==0,"little","big") 
        id <- .bracketRange(hdr, "spectra names")

```
and 
`x[] <- readBin(path, "numeric", n = 1e+06, size = bytes)`
to
` x[] <- readBin(path, "numeric", n = 1e+06, size = bytes,endian=byte_order)`

**Comment by bleutner** [comment]
Well done, thanks! Fixed now.
