### ISSUE TITLE
Use prcomp() in rasterPCA

### ISSUE THREAD

**Issue by aloboa** [bleutner/RStoolbox#49]
rasterPCA is based on princomp(), but (from the princomp help page)
"The calculation is done using eigen on the correlation or covariance matrix, as determined by cor. This is done for compatibility with the S-PLUS result. A preferred method of calculation is to use svd on x, as is done in prcomp."

I thus suggest using prcomp() in rasterPCA()

**Comment by bleutner** [comment]
prcomp is not a suitable choice for large remote sensing data sets as it operates on X as opposed to princomp which operates on the correlation or covariance matrix, both of which can be computed in a piecewise fashion. I.e. for prcomp you'd have to load all data into memory at once, while for princomp you can first compute the covariance matrix and the run eigen on it, which is not only faster, but more importantly memory-safe. 

In the end the results of both methods are equal. While numerical differences can exist, with SVD being more accurate, this is generally negligible compared to the measurement uncertainty inherent in typical remote sensing data.
