### ISSUE TITLE
Output eigenvectors in rasterPCA

### ISSUE THREAD

**Issue by aloboa** [bleutner/RStoolbox#50]
I often miss eigenvectors in the rasterPCA() output (pcomp$rotation or princomp$loadings),
in addition to the eigenvalues currently provided.

**Comment by bleutner** [comment]
The loadings are present in the output already:
```
rpa <- rasterPCA(...)
rpa.loadings <- loadings(rpa$model)
```

**Comment by aloboa** [comment]
Great. Please note it in the help page.
Currently it states that the output is just a raster brick and when your run the summary() of the example
there is no mention that other information other than that  derived from eigenvalues is actually available.
