### ISSUE TITLE
readSLI collapses " " from "spectra names" in hdr files to ""

### ISSUE THREAD

**Issue by aloboa** [bleutner/RStoolbox#52]
Currently, *.sli files from EnMapBox come with "spectra names" field in the corresponding  *.hdr file that have " " separators, such as:
spectra names = {
 FX10FX17_Quartz1_small.raw 738.785219770416 358.03143995717653 USER:100025, 
 FX10FX17_Quartz2_small.raw 615.0409742461194 446.71481591625576 USER:100025, 
 FX10FX17_Quartz3_small.raw 346.9284422768101 586.9582941771253 USER:100025}
readSLI() collapses the " " and names become:                                                     
[2] "FX10FX17_Quartz1_small.raw738.785219770416358.03143995717653USER:100025" 
[3] "FX10FX17_Quartz2_small.raw615.0409742461194446.71481591625576USER:100025"
[4] "FX10FX17_Quartz3_small.raw346.9284422768101586.9582941771253USER:100025" 

which is very inconvenient for ulterior processing. Could you use "_" as separator?
"FX10FX17_Quartz1_small.raw_738.785219770416_358.03143995717653_USER:100025" 
"FX10FX17_Quartz2_small.raw_615.0409742461194_446.71481591625576_USER:100025"
"FX10FX17_Quartz3_small.raw_346.9284422768101_586.9582941771253_USER:100025"

**Comment by bleutner** [comment]
good idea
