### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by aloboa** [bleutner/RStoolbox#53]
As a test, I'm running rasterPCA() with a raster image of 8282 * 11329 * 5 on 
a machine with 64 Gb of RAM and it takes longer
than I had expected. I can see that the process does not take more than 2.4 Gb of RAM
Do you have any kind of memory management limits that could make that rasterPCA()
would not be taking as much RAM as it could?
Thanks

**Comment by bleutner** [comment]
We rely on the memory management of the raster package. Hence, you can use `rasterOptions()` to increase `maxmemory` (number of pixels to read into memory).
E.g. `rasterOptions(maxmemory=1e9)`

**Comment by aloboa** [comment]
ok!
