### ISSUE TITLE
Spectral Mixture Analysis

### ISSUE THREAD

**Issue by ytarazona** [bleutner/RStoolbox#57]
Thank you for the spectral unmixing function. However, I think the assignment of the name "mesma" seems to be wrong!. Since mesma means that multiple endmembers get the lowest RMSE. I executed the mesma function of RStoolbox for a total of 100 endmembers and the result is the number of fractions equal to the number of endmembers. Please I suggest to change the name of the function because "mesma" means to choose the endmember with the lowest RMSE from a set of endmembers. For more details see: [Somers et al. 2011](https://doi.org/10.1016/j.rse.2011.03.003).

If I'm wrong, please let me know.
Best regards,

**Comment by GreatEmerald** [comment]
Yes, I'm confused about that as well. The example in the docs only shows a single endmember per class. I assumed that you could add more endmembers per class if you used the same name for each row, but that just makes the output have "name.1" as a class. It would be nice if you could clarify whether this is just regular SMA or alternatively add a bigger example that uses multiple endmembers per class.

**Comment by 16EAGLE** [comment]
Thanks for flagging this. This has been addressed with the most recent update: For single endmember unmixing, each supplied endmember now represents a class to unmix (row by row). For multiple endmemeber unmixing, the column `class` can be used to group endmembers by class. If multiple endmembers per class are provided, `mesma()` will compute a number of SMA (determined through the new argument `n_models`) for multiple endmember combinations drawn from endmembers and will select the best fit per pixel based on the lowest RMSE.

See https://github.com/bleutner/RStoolbox/blob/master/NEWS.md#rstoolbox-041 for further info on the changes and `?RStoolbox::mesma` after updating to the most recent github version.
