### ISSUE TITLE
Additional facet_wrap arguments to ggR()

### ISSUE THREAD

**Issue by RS-eco** [bleutner/RStoolbox#58]
I would like to plot multiple layers with ggR():

```{r}
ggR(lsat, 1:3, geom_raster=TRUE, stretch = "lin") +
    scale_fill_gradientn(colors=grey.colors(100), guide = FALSE) +
    theme(axis.text = element_text(size=5), 
          axis.text.y = element_text(angle=90),
          axis.title=element_blank())
```

But would like the subplots to appear in one column rather than one row.
Would it be possible to extend the function to an additional argument (ncol, nrow) that feeds into the facet_wrap() function. If you like, I can also issue a pull request for this.

**Comment by bleutner** [comment]
I'm not decided yet, as I don't want to duplicate too many ggplot2 arguments.
In the meantime, you can append your own custom facet_wrap like this ("layerName" is the internal variable name):

```r
ggR(lsat, 1:3, geom_raster=TRUE, stretch = "lin") +
		scale_fill_gradientn(colors=grey.colors(100), guide = FALSE) +
		theme(axis.text = element_text(size=5), 
		axis.text.y = element_text(angle=90),
		axis.title=element_blank()) +
		facet_wrap(~layerName, ncol=2)
```

**Comment by RS-eco** [comment]
Thanks, I knew there was something that I was missing. This should do they trick and save you from duplicating any of the arguments.
