### ISSUE TITLE
Error message while computing spectral indices

### ISSUE THREAD

**Issue by mej1d1** [bleutner/RStoolbox#6]
I created a raster stack (landsat_data) with 6 layers, each of which represents one band.I also saved the names of the layers in a vector (names_landsat). Now I want to calculate the spectral indices with the following code:

```
    ind <- landsat_data
    ind <- spectralIndices(ind,blue=as.character(names_landsat[1]),green=as.character(names_landsat[2]),red=as.character(names_landsat[3]),nir=as.character(names_landsat[4]),swir1=as.character(names_landsat[5]),swir2=as.character(names_landsat[6]))

```
Unfortunately R returns the following error message:

  ```
  Error in if ((maxValue(img[[red]])/scaleFactor > 1.5 | minValue(img[[red]])/scaleFactor <  : 
      missing value where TRUE/FALSE needed
    In addition: Warning messages:
    1: In .local(x, ...) : max value not known, use setMinMax
    2: In .local(x, ...) : min value not known, use setMinMax

```
I have absolutely zero clue what that means as I am pretty new to this package.
I would be very grateful if somebody could give me any kind of help.
Thanks.

**Comment by bleutner** [comment]
Looks like this needs more careful heuristics on my side --> I'll refine that in one of the next versions.  It should only occur though when EVI or EVI2 are to be calculated.

For now please set the data range beforehand, i.e. run this once after you load the data,

```r
## Reads the raster once to get accurate minimum and maximum values
landsat_data <- setMinMax(landsat_data)

# And then as usual 
indices <- spectralIndices(landsat_data, blue = 1, green=2, red =3 )

```

**Comment by mej1d1** [comment]
Thanks for your reply ! I did as advised and now I et the following warning message:

```
Warning message:
In spectralIndices(ind, blue = names_landsat[1], green = names_landsat[2],  :
  EVI/EVI2 parameters L_evi, G, C1 and C2 are defined for reflectance [0,1] but img values are outside of this range.
  If you are using scaled reflectance values please provide the scaleFactor argument.
  If img is in DN or radiance it must be converted to reflectance.
  Skipping EVI calculation.
```

Does this mean that all indices except for EVI are calculated ?

**Comment by bleutner** [comment]
Yes that is what it is supposed to tell you, when your data do not look like reflectance values. 

EVI and EVI2 rely on parameters which are defined for reflectance values only (ranging from 0 to 1). 
If your data are actually reflectances, but are scaled to a different range, e.g. 0-1000 you can still calculate EVI by supplying the scaling factor, i.e. in this example scaleFactor=1000.

However, if your data are not reflectances, but digital numbers (DN), for example, EVI is not defined and hence will not be calculated.

**Comment by mej1d1** [comment]
oh ok I understand. Did you see my edit ? EVI is not the only one not being computed. Excuse me if my questions may sound stupid, but as I already said, I'm pretty new to all this.

**Comment by bleutner** [comment]
Only EVI and EVI2 should be skipped in this case. Are there any others missing?

**Comment by mej1d1** [comment]
Yes, only 13 indices are being returned. According to the help file for the `spectralIndices()` function, they should be 22 (if I counted correctly).

**Comment by bleutner** [comment]
Thanks, that was indeed a bug. I've updated the package. The next release is not yet due. To calculate the missing indices for now please install the current Github version.

**Comment by mej1d1** [comment]
Ok, thanks. Where can I find the Github version ?

**Comment by bleutner** [comment]
here ;-)

https://github.com/bleutner/RStoolbox

**Comment by mej1d1** [comment]
Awesome, thanks a lot!

**Comment by mej1d1** [comment]
sorry to bother you again, but now (after installing the latest GitHub version) i get 19 indices instead of 20 (total number of indices is 22 according to the help file, so without the two EVI indices a total of 20 indices should be returned, right?).

**Comment by bleutner** [comment]
I guess you did not specify the coefficients  swir2coc (completely open canopy) and swir2ccc (completely closed canopy) which are required in order to calculate NDVIC. 
Some people simply use min and max values of the SWIR2 band and I could do this automatically, however this can be misleading if for example you have water bodies in your scene. Therefore, these must be specified manually by the user.

I probably should make this more clear in the documentation.

**Comment by mej1d1** [comment]
ok, I understand. Thanks again for helping me out!

**Comment by gtalckmin** [comment]
@bleutner :
is there a way I could add a vegetation index to the list of indices, without editing the C++ code within the package ?
