### ISSUE TITLE
Interpretation of `mesma` probabilities >1

### ISSUE THREAD

**Issue by michaeldorman** [bleutner/RStoolbox#62]
According to the `mesma` documentation, returned values are expected where "each value representing the estimated presence probability of the endmember per pixel (**0 to 1**)".  However, the resulting rasters in the provided example have values that are **>1**:

```r
library(raster)
library(RStoolbox)
data(lsat)
em_names <- c("water", "land")
pts <- data.frame(class=em_names, cell = c(47916,5294))
em <- lsat[pts$cell]
rownames(em) <- em_names
probs <- mesma(lsat, em, method = "NNLS")
range(probs[[1]][], na.rm = TRUE)
## [1] 0.000000 1.024394
range(probs[[2]][], na.rm = TRUE)
## [1] 0.000000 1.543188
```

My question is on how to interpret this. Is this expected behavior? If so, should the values just be truncated so that any probability >1 becomes 1? If not, is this potentially a bug?

Thanks!

**Comment by Joy-Giovanni** [comment]
I also have the same question, In my current project values were not only >1, they were in thousands. @16EAGLE can you help?

**Comment by BillyBrowning1** [comment]
Was this ever solved? Same question here

**Comment by 16EAGLE** [comment]
This has been solved with the most recent update, implementing a sum-to-one constraint on top of `NNLS`. See https://github.com/bleutner/RStoolbox/blob/master/NEWS.md#rstoolbox-041 and `?RStoolbox::mesma` after updating to the most recent github version for details.
