### ISSUE TITLE
Error in !res[[1]]

### ISSUE THREAD

**Issue by deryagulcinubc** [bleutner/RStoolbox#70]
It does not matter which function of RStoolbox I use, every time I got this error below:

Error in !res[[1]] : invalid argument type

For instance, I tried to open the landsat 8 image that I downloaded from usgs's website:

setwd("C:\\myPath\\myolder")
metaData_pre <- readMeta("LC08_L1TP_183033_20170730_20170811_01_T1\\LC08_L1TP_183033_20170730_20170811_01_T1_MTL.txt")

Here is the error:
Error in !res[[1]] : invalid argument type

**Comment by bleutner** [comment]
Sorry I didn't manage to respond.
Please re-open this ticket if your issue is still relevant.
