### ISSUE TITLE
readMeta fails to read Landsat 8 MSS metadata (*MTL.txt) files

### ISSUE THREAD

**Issue by jkoellin** [bleutner/RStoolbox#71]
Hello bleutner,

thanks for your work with the Toolbox, it helped me in the past.

I have a problem with my new project. I try to read landsat8 data with the `readMeta` function and I get an error message. 

This is my code: 

```
install.packages("RStoolbox")
library(devtools)
install_github("bleutner/RStoolbox")
library(RStoolbox)
metaData_prefire <- readMeta("C:\\Users\\le-ob-dual-1\\Desktop\\Studium\\Ulluoa\\Semesterprojekt\\R_Program\\LC08_L1TP_193024_20180824_20200831_02_T1_richtig\\LC08_L1TP_193024_20180824_20200831_02_T1_MTL.txt")

```
and this is the error message I get: 
```
Fehler in CRS(paste0(c("+proj=", "+zone=", "+units=m +datum="), pars, collapse = " ")) : 
  No spaces permitted in PROJ4 argument-value pairs: +proj= +zone= +units=m +datum=
```

my file was downloaded from the earthexplorer and I Included it: 
[LC08_L1TP_193024_20180824_20200831_02_T1_MTL.txt](https://github.com/bleutner/RStoolbox/files/5786478/LC08_L1TP_193024_20180824_20200831_02_T1_MTL.txt)
Do you have any suggestions, how I could read Landsat8 files like that or maybe have a idea, what causes the error? 

Thanks,
 Jonas

**Comment by RichardLemoine** [comment]
Dear @bleutner,

adittionally to this, I'm experiencing the following error when trying to read the metadata of a Landsat 8 **collection 2** image:

`library(RStoolbox)
meta <- readMeta("E:/Landsat/LC08_L1TP_025046_20190412_20190422_02_T1_MTL.txt")`

Error in as.POSIXct.default(if (!legacy) meta$PRODUCT_METADATA["DATE_ACQUIRED",  : 
  c("do not know how to convert 'if (!legacy) meta$PRODUCT_METADATA[\"DATE_ACQUIRED\", ] else meta$PRODUCT_METADATA[\"ACQUISITION_DATE\", ' to class “POSIXct”", "do not know how to convert '    ]' to class “POSIXct”")

I think that the error should be due to a change in the structure of the metada in collection 2 in comparison to collection 1. I tested with the same scene from collection 1 and it works as expected. I hope this is an eassy to solve issue.

Regards,
Richard

**Comment by jgomezd** [comment]
Dear Bleutner,

I am also having the problem that the previous people report when reading a Landsat 8 Image Level 2 of Collection 2:

library(RStoolbox)
M <- readMeta("imagen_satelite/LC08_L2SP_025046_20210127_20210305_02_T1_MTL.txt")

I have the following message:
Error in CRS(paste0(c("+proj=", "+zone=", "+units=m +datum="), pars, collapse = " ")) : 
  No spaces permitted in PROJ4 argument-value pairs: +proj= +zone= +units=m +datum=

R version 4.0.4 (2021-02-15) -- "Lost Library Book"
RStoolbox version 0.2.6 
Windows 10, x64

**Comment by RikFerreira** [comment]
Dear @bleutner,

I'm experiencing exactly the same issue related previously with the MTL relative to Landsat 5 TM image `LT05_L1TP_218072_20100801_20161015_01_T1` downloaded from USGS.

For the record, the MTL file from Landsat 5 TM image `LT05_L1TP_218072_20100716_20161014_01_T1` works just as expected.

- [Working file](https://gist.github.com/RikFerreira/1c86f4321bcd17beea23eac175ab09c5)
- [Bad file](https://gist.github.com/RikFerreira/7936d3eedf772014405a3731c3b5c758)
- [Diff](https://gist.github.com/RikFerreira/68a36700301c01fa73ebdc9cedff2d3a)

Does anyone who went through this problem found any solution?

Thank you all for your time,
Rik

**Comment by FelipeTC91** [comment]
Dear @bleutner

I have the same problem with the MTL file for landsat 8

CRS(paste0(c("+proj=", "+zone=", "+units=m +datum="), pars, collapse = " ")) : 
  No spaces permitted in PROJ4 argument-value pairs: +proj= +zone= +units=m +datum=

I really appreciate your help with this error

Thanks

**Comment by jjarosch** [comment]
The projection error arises here: https://github.com/bleutner/RStoolbox/blob/7b85a191caa9eab85ae72e8ce9c97555fb533fa0/R/readMeta.R#L69
The group/slot is now called `LEVEL1_PROJECTION_PARAMETERS`. A number of groups have `LEVEL1_` prefixed in Collection 2.

**Comment by bleutner** [comment]
Thanks everyone for your reports. Fixed now.
