### ISSUE TITLE
ShiftEstimate

### ISSUE THREAD

**Issue by Saadi4469** [bleutner/RStoolbox#72]
Hello,

In a lot of the examples, I see shiftEstimate[-16,-6] in "CloudShadowMask", from where do you get these values? In case of Landsat 8 Level 1 Collection1, is it safe to use these x-y values for shiftEstimate?

Thank you,

**Comment by bleutner** [comment]
The shift estimate has to be estimated interactively for each scene. It depends on cloud altitude and solar geometry. Have a look at the examples under `?cloudShadowMask` on how to do that.
