### ISSUE TITLE
Error thrown when validation and training data are different classes.

### ISSUE THREAD

**Issue by Silviculturalist** [bleutner/RStoolbox#73]
I found that there's an error that arises from the invalid !all.equal that is thrown when the two input classes are of different class.

From the help on base::all.equal you can read: 

"Do not use all.equal directly in if expressions—either use isTRUE(all.equal(....)) or identical if appropriate."

Is there any particular reason one should not be able to provide the function with for example training data in SpatialPolygonsDataFrame and validate with a SpatialPointsDataFrame?

https://github.com/bleutner/RStoolbox/blob/7b85a191caa9eab85ae72e8ce9c97555fb533fa0/R/superClass.R#L117

**Comment by bleutner** [comment]
no real reason. too late for you I guess, but it is possible from now on
