### ISSUE TITLE
ggR change color

### ISSUE THREAD

**Issue by Saadi4469** [bleutner/RStoolbox#75]
Hello, 

Is it possible to change the color of the plot while plotting a raster? The only option seems to be in grey scale.

Thank you,

**Comment by bleutner** [comment]
see ?ggR

For example, you can add any fill_scale (if geom_raster=TRUE)
```r
data(lsat)
ggR(lsat, layer = 4, geom_raster = TRUE) +
    scale_fill_viridis_c()
```
or alternatively tinted monochrome
```r
ggR(lsat, layer = 4, hue = 0.5, sat = 1)
```
