### ISSUE TITLE
incorrect value in res$model$n.obs

### ISSUE THREAD

**Issue by andliszmmu** [bleutner/RStoolbox#79]
Hello,
Result of rasterPCA (res in my example contains a value res$model$n.obs. It should be a real number of observations, it seems to me. But it is a number of cells in one raster, if nSamples was not set. It is not difficult to access number of cells, so such value is not useful. If my raster stack contains a lot of NAs, real number of observations is less and would be a useful value to understand how many rows really participated in PCA.
It would be very useful, if this issue will be solved. Thank you

**Comment by andliszmmu** [comment]
if(!is.null(nSamples)){    ...  }
else
{ ... model$n.obs  <- ncell(img) ...}
probably length(img[!is.na(img)]) is better... ncell ignores na

**Comment by andliszmmu** [comment]
In fact, rasterPCA never works in my case if nSamples is close to length(img[!is.na(img)])
>length(train.stack[[1]][!is.na(sum(train.stack))])
7087
>cat("\n", ns.pc, " ", nlayers(train.stack), "\n")
7087 85
>train.pc         <- rasterPCA(train.stack, nSamples = ns.pc, maskCheck=F, spca = T)
Error in rasterPCA(train.stack, nSamples = ns.pc, maskCheck = F, spca = T) :
  nSamples too small or img contains a layer with NAs only
I have no idea, where is the error. Peculiarity of my rasters - a lot of NAs

**Comment by bleutner** [comment]
Good catch. Thank you; fixed now
