### ISSUE TITLE
Training data error superClass

### ISSUE THREAD

**Issue by Saadi4469** [bleutner/RStoolbox#83]
I am trying to perform a `supervised classification` using `polygon spatial data` and a `RGB` raster. However, I am getting the following error even though `rgdal` picks up the shapefile as a `SpatialPolygonsDataFrame`.

How can I fix this?

Error
`Error: traingData must POINTs or a POLYGONs`

Code

```
SC_RF = superClass(img = CR, model = "rf", trainData = Training_Data,
                         responseCol = "Feature")
```

![image](https://user-images.githubusercontent.com/55733842/171453110-fca213fc-c8ab-46b7-af57-5e3d3861e173.png)

**Comment by KonstiDE** [comment]
Since `rGDAL` is now archived and the `RStoolbox` does no longer depend on it, problems should have resolved themselves. Please let me know if not :)
