### ISSUE TITLE
Please attend to retirement of rgdal, rgeos and maptools

### ISSUE THREAD

**Issue by rsbivand** [bleutner/RStoolbox#85]
See: https://r-spatial.org/r/2022/04/12/evolution.html. **sp** on CRAN now offers control of the environment variable, so the attached log is from `_SP_EVOLUTION_STATUS_=2 _R_CHECK_FORCE_SUGGESTS_=FALSE R CMD check RStoolbox_0.3.0.tar.gz`:
[00check.log](https://github.com/bleutner/RStoolbox/files/9055839/00check.log)

**Comment by KonstiDE** [comment]
Hi, with v0.4.0, all outdated things should have been thrown out
