### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [bleutner/RStoolbox#90]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by erikmeesters** [comment]
install fails because rgdal can no longer be downloaded.

**Comment by rsbivand** [comment]
@nedhorning @bleutner @erikmeesters  No action was taken on my very early warning a year ago (this issue). The package could have been kept active had steps been taken before June/October 2023 to remove retiring package `rgdal`. Since `rgdal` was archived October 16, obviously `RStoolbox` cannot be installed. This is a check log from a modified version of RStoolbox without `rgdal` in `DESCRIPTION`, showing the earlier problems leading to `RStoolbox` being archived from CRAN in February 2023: 
[00check.log](https://github.com/bleutner/RStoolbox/files/13752321/00check.log)

**Comment by bleutner** [comment]
Hi Roger, Erik, 
we're aware of this. The transition had already been initiated,  but stopped since I have currently 0 time to do anything here. We do have a new contributor who has picked up the threads and is going to reactivate that package to CRAN hopefully soon.
