### ISSUE TITLE
CRAN Archival 2023-02-12

### ISSUE THREAD

**Issue by idblr** [bleutner/RStoolbox#95]
RStoolbox was [archived on CRAN](https://cran.r-project.org/package=RStoolbox) as of 2023-02-12 with these [CRAN check results](https://cran-archive.r-project.org/web/checks/2023/2023-02-12_check_results_RStoolbox.html). Do you have an estimate of if/when this will be reconciled? Thank you!

**Comment by CCheCastaldo** [comment]
I have the same question @bleutner. I cannot seem to install this from source given all its various system file dependencies (gfortran etc) and the binary is no longer available on CRAN. Do you have a sense of when this will be fixed or perhaps some instructions on how to get this package installed from source? Thanks.

**Comment by CCheCastaldo** [comment]
Just curious - has this package abandoned? Cannot install 0.3.0 from source on an M2 mac and there are not any instructions on how to do this. thanks.

**Comment by bleutner** [comment]
Hi Friends, 
I'm very sorry for keeping you waiting. It is not technically abandoned, but I'm currently struggling to find any free time to work on this beside my regular job. The transition to terra is about half way through, but I cannot promise yet when I'll be able to pick it up again. 
I do welcome pull requests if someone wants to help out.
Cheers
Benjamin

**Comment by KonstiDE** [comment]
Hello, RStoolbox will be resubmitted to CRAN in during the next days / weeks

**Comment by bleutner** [comment]
Awesome! Thanks @KonstiDE

**Comment by KonstiDE** [comment]
The RStoolbox is now back on CRAN [https://cran.r-project.org/package=RStoolbox](here).
Closing this issue :)
